sudo: false
language: php

php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install

services:
  - elasticsearch

before_script:
  - sleep 5

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bin/coveralls -v