sudo: false
language: php

php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

services:
  - elasticsearch

before_script:
  - sleep 10

before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.1/elasticsearch-2.4.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.1.deb && sudo service elasticsearch restart

script: phpunit